### ISSUE TITLE
Créer le protocole `display()`

### ISSUE THREAD

**Issue by PaullyUlisses** [Index-True/plouf-war#7]
# Description du `display()`
## Paramètres
`screen` : le plateau du joueur 1 ou 2
`viewer` : un boolean précisant si le plateau est regardé par son propriétaire ou son adversaire

**Comment by Index-True** [comment]
Yop comme parametres tu veux pas remplacer screen par `grids` et viewer par `playerId` histoire d'avoir les memes noms de variables partout et tu pourra regarder dans [main.py](https://github.com/Index-True/plouf-war/blob/dev/main.py#14) pour regarder comment utiliser les grilles
